name: Dependent Jobs Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "name=hany from github actions" >> ${GITHUB_ENV}

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${name} from github actions"
