name: Upload Artifact

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Hello Ahmed" > result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-result
          path: result.txt