name: Workflow Commands Demo

on:
  workflow_dispatch:

jobs:
  commands-demo:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Notice
        shell: pwsh
        run: |
          Write-Output "::notice::Workflow Started Successfully"

      - name: Warning
        shell: pwsh
        run: |
          Write-Output "::warning::This is just a warning"

      - name: Error (Demo Only)
        shell: pwsh
        run: |
          Write-Output "::error::This is a fake error message"

      - name: Group Logs
        shell: pwsh
        run: |
          Write-Output "::group::Installing Dependencies"
          Write-Output "Installing Python..."
          Write-Output "Installing Packages..."
          Write-Output "Finished."
          Write-Output "::endgroup::"

      - name: Mask Secret
        shell: pwsh
        run: |
          Write-Output "::add-mask::Ahmed123456"
          Write-Output "Password = Ahmed123456"

      - name: Create Environment Variable
        shell: pwsh
        run: |
          "USERNAME=Ahmed" >> $env:GITHUB_ENV

      - name: Read Environment Variable
        shell: pwsh
        run: |
          Write-Output "User: $env:USERNAME"

      - name: Create Output
        id: my_step
        shell: pwsh
        run: |
          "score=100" >> $env:GITHUB_OUTPUT

      - name: Read Output
        shell: pwsh
        run: |
          Write-Output "Score = ${{ steps.my_step.outputs.score }}"

      - name: Workflow Summary
        shell: pwsh
        run: |
          @"
          # Workflow Finished ✅

          ## Information
          - Runner: Self-hosted
          - User: Ahmed
          - Score: 100

          Workflow completed successfully.
          "@ >> $env:GITHUB_STEP_SUMMARY